from __future__ import annotations

from .common import *


def write_paper_reports(
    study_tables: dict[str, pd.DataFrame],
    benchmark_result: ImputationResult,
    task_result: ImputationResult,
    included_benchmarks: list[str],
    mini_leaderboard_figures: list[str],
) -> None:
    filter_table = study_tables["benchmark_filtering"]
    provenance = study_tables["analysis_data_provenance"]
    agent_model_scores = study_tables["benchmark_agent_model_scores"]
    model_effects = study_tables["benchmark_model_adjusted_effects"]
    agent_effects = study_tables["benchmark_agent_adjusted_effects"]
    variance_filtered = study_tables["benchmark_variance_decomposition_filtered"]
    benchmark_role = study_tables["benchmark_model_agent_role_by_benchmark"]
    benchmark_clusters = study_tables["benchmark_similarity_clusters"]
    redundancy = study_tables["benchmark_redundancy_pairs_filtered"]
    uniqueness = study_tables["benchmark_uniqueness_filtered"]
    agent_lift = study_tables["benchmark_agent_lift_vs_terminus"]
    terminus_by_model = study_tables["terminus_delta_by_model"]
    task_summary = study_tables["task_benchmark_reliable_summary"]
    alignment = study_tables["task_to_benchmark_alignment"]
    task_similarity = study_tables["task_within_benchmark_similarity"]
    task_cross_similarity = study_tables["task_cross_benchmark_similarity"]
    representative_tasks = study_tables["task_representative_tasks"]
    task_predictability = study_tables["task_predictability_ranked"]
    selected_tasks = study_tables["harbormix_candidate_tasks"]
    selection_by_benchmark = study_tables["harbormix_selection_by_benchmark"]

    excluded = filter_table[~filter_table["include_in_paper_analysis"]]
    redundant_high = redundancy[redundancy["spearman"] >= 0.75].sort_values("spearman", ascending=False)
    unique_low = uniqueness.sort_values("cv_r2_from_other_included_benchmarks")
    alignment_good = alignment[
        alignment["included_in_benchmark_level_paper_filter"] & (alignment["n_reliable_bounded_tasks"] >= 3)
    ].sort_values("spearman_agent_model_correlation", ascending=False)
    task_pool = task_summary.sort_values("candidate_pool_tasks", ascending=False)
    role_gap = benchmark_role.assign(
        absolute_role_gap=lambda df: (df["model_partial_r2_over_agent"] - df["agent_partial_r2_over_model"]).abs()
    ).sort_values("absolute_role_gap", ascending=False)
    hard_tasks = task_predictability.sort_values("task_unpredictability_score", ascending=False)
    representative_top = representative_tasks.sort_values("representativeness_score", ascending=False)
    code_files = [
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'analysis.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'figures.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'reports.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'pipeline.py')}`",
    ]

    report_lines = [
        "# Paper-Facing Cross-Benchmark Analysis",
        "",
        "This report is intended to be read directly. Figures and compact table previews are embedded inline; CSV paths are listed for exact numbers and reproducibility.",
        "",
        "## Directory Contract",
        "",
        f"- Paper-facing tables: `{md_path(PAPER_TABLE_DIR)}/`",
        f"- Paper-facing figures: `{md_path(PAPER_FIGURE_DIR)}/`",
        f"- Expanded study outputs: `{md_path(STUDY_DIR)}/`",
        f"- Intermediate imputed matrices and diagnostics: `{md_path(PROCESSED_DIR)}/`",
        "",
        "Missingness in this report means original raw-data coverage before SVD filling. The processed SVD matrices are dense; observed-count and missingness columns are retained so we can distinguish measured evidence from model-completed cells.",
        "",
        "Data provenance for the main studies:",
        "",
        *markdown_table(provenance, ["analysis", "primary_matrix", "processed_output"], 10),
        "",
        "## Study 1: Coverage Filtering",
        "",
        "**Method:** Benchmark-level claims use only columns with at least 15 observed agent+model rows and at most 45% original raw-data missingness. The SVD-filled processed matrix is dense, but this filter keeps the paper story from leaning too heavily on filled values.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_filtering.csv')}`",
        "",
        "**Result overview and analysis:**",
        f"- Included {len(included_benchmarks)} of {len(filter_table)} benchmarks.",
        f"- Excluded sparse benchmarks: {', '.join(excluded['benchmark'].tolist())}.",
        f"- Benchmark matrix imputation used rank {benchmark_result.best_rank}; raw benchmark missing fraction was {benchmark_result.missing_fraction:.3f}.",
        "",
        *markdown_table(filter_table, ["benchmark", "include_in_paper_analysis", "observed_count", "missing_fraction"], 12),
        "",
        "**Insight and findings:** Sparse columns should stay in appendix/provisional analysis until more experiments land. The main paper story should use the coverage-filtered benchmark set.",
        "",
        "## Study 2: Model vs Agent Roles",
        "",
        "**Method:** I fit fixed-effect regressions in two views. The overall view decomposes benchmark-relative score into model, agent, benchmark, and interaction terms. The per-benchmark view fits each benchmark separately and compares partial R2 from model after controlling for agent against partial R2 from agent after controlling for model.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_variance_decomposition_filtered.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_model_agent_role_by_benchmark.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_model_adjusted_effects.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_agent_adjusted_effects.csv')}`",
        "",
        report_image("benchmark_variance_attribution.png", "Benchmark-level variance attribution"),
        "",
        report_image("benchmark_model_vs_agent_role.png", "Per-benchmark model vs agent explanatory power"),
        "",
        report_image("benchmark_model_adjusted_effects.png", "Model effects adjusted for agent and benchmark"),
        "",
        report_image("benchmark_agent_adjusted_effects.png", "Agent effects adjusted for model and benchmark"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(variance_filtered, ["component", "partial_r2_over_other_main_effects", "r2", "type"], 7),
        "",
        "Benchmarks with the largest model-vs-agent role imbalance:",
        *markdown_table(role_gap, ["benchmark", "model_partial_r2_over_agent", "agent_partial_r2_over_model", "dominant_dimension"], 10),
        "",
        "**Insight and findings:** Model identity explains much more overall variation than agent identity, but the role varies by benchmark. Agent effects are more useful as benchmark-specific harnessing effects than as a universal main effect.",
        "",
        "## Study 3: Agent+Model Leaderboards",
        "",
        "**Method:** I keep `agent+model` rankings as descriptive mini-leaderboards. Per-benchmark mini-leaderboards use SVD-filled raw benchmark scores on each benchmark's original metric scale. The aggregate top-agent plot uses mean within-benchmark raw-score percentile, because averaging raw scores across benchmarks with different scales would be misleading.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_agent_model_scores.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_raw_scores_long.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_mini_leaderboards.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_similarity_clusters.csv')}`",
        f"- `{md_path(PAPER_FIGURE_DIR / 'mini_leaderboards_cluster_*.png')}`",
        "",
        report_image("benchmark_agent_model_top_scores.png", "Top agent+model pairs on included benchmarks"),
        "",
        *[report_image(fig, f"Mini-leaderboards {fig}") for fig in mini_leaderboard_figures],
        "",
        "**Result overview and analysis:**",
        *markdown_table(agent_model_scores, ["rank", "agent_model", "mean_raw_score_percentile_across_benchmarks", "observed_fraction_on_included_benchmarks"], 10),
        "",
        "**Insight and findings:** Raw benchmark scores should be read benchmark by benchmark. The percentile aggregate is a compact descriptive ranking only; it is not a causal agent claim because model and agent are entangled in the row identity.",
        "",
        "## Study 4: Benchmark Predictability and Similarity",
        "",
        "**Method:** Following the BenchPress idea, each included benchmark is predicted from the other included benchmarks using ridge regression with cross-validation over agent+model rows. Low or negative R2 means the benchmark is hard to reconstruct from the rest and likely contributes distinct information. Benchmark similarity uses Spearman correlation of agent+model score profiles and hierarchical clustering.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_uniqueness_filtered.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_redundancy_pairs_filtered.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_correlation_clustered.csv')}`",
        "",
        report_image("benchmark_uniqueness_vs_coverage.png", "Benchmark uniqueness after coverage filtering"),
        "",
        report_image("benchmark_similarity_clustered_heatmap.png", "Clustered benchmark similarity heatmap"),
        "",
        "**Result overview and analysis:**",
        "Hardest-to-predict benchmarks:",
        *markdown_table(unique_low, ["benchmark", "cv_r2_from_other_included_benchmarks", "cv_rmse"], 10),
        "",
        "Most similar benchmark pairs:",
        *markdown_table(redundant_high, ["left", "right", "spearman"], 10),
        "",
        "**Insight and findings:** Predictable benchmarks are candidates for compression; hard-to-predict benchmarks should be preserved when the goal is behavioral breadth. Similarity clusters are also the basis for the grouped mini-leaderboards.",
        "",
        "## Study 5: Task Similarity, Predictability, and Representatives",
        "",
        "**Method:** Task-level analysis uses reliable, bounded, non-degenerate tasks only. A task is hard to predict when its maximum absolute Spearman correlation to peer tasks in the same benchmark is low. A representative task is one whose score profile correlates strongly with the benchmark's reliable-task aggregate. Within- and cross-benchmark task similarity use median absolute task-profile correlations.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(PAPER_TABLE_DIR / 'task_predictability_ranked.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'task_representative_tasks.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'task_within_benchmark_similarity.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'task_cross_benchmark_similarity.csv')}`",
        "",
        report_image("task_hard_to_predict_ranked.png", "Hard-to-predict reliable tasks"),
        "",
        report_image("task_best_representatives.png", "Best representative task per benchmark"),
        "",
        report_image("task_similarity_benchmark_pair_heatmap.png", "Task similarity across benchmark pairs"),
        "",
        "**Result overview and analysis:**",
        "Hardest-to-predict reliable tasks:",
        *markdown_table(hard_tasks, ["benchmark", "task_id", "task_unpredictability_score", "difficulty_tier", "observed_mean"], 12),
        "",
        "Most representative tasks:",
        *markdown_table(representative_top, ["benchmark", "task_id", "representativeness_score", "difficulty_tier", "observed_mean"], 12),
        "",
        "Benchmarks with strongest within-benchmark task similarity:",
        *markdown_table(task_similarity, ["benchmark", "n_reliable_tasks", "median_abs_task_similarity_within_benchmark"], 10),
        "",
        "**Insight and findings:** Task predictability and representativeness are different objectives. Representative tasks are good compact proxies for a benchmark; hard-to-predict tasks are better stress tests for broad coverage.",
        "",
        "## Study 6: Terminus Harnessing Effects",
        "",
        "**Method:** Terminus is treated as the fair baseline across models. For every model with both `terminus-2` and another agent row, I compute paired benchmark-relative score deltas while holding the model fixed.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(PAPER_TABLE_DIR / 'benchmark_agent_lift_vs_terminus.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'terminus_delta_by_model.csv')}`",
        f"- `{md_path(BENCHMARK_STUDY_DIR / 'benchmark_agent_lift_by_benchmark.csv')}`",
        "",
        report_image("benchmark_agent_lift_heatmap.png", "Agent lift vs terminus by benchmark"),
        "",
        report_image("terminus_delta_by_model_heatmap.png", "Agent lift vs terminus by model"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(agent_lift, ["agent", "mean_delta_vs_terminus", "win_rate_vs_terminus", "compared_models"], 6),
        "",
        *markdown_table(terminus_by_model, ["model", "agent", "mean_delta_vs_terminus", "win_rate_vs_terminus"], 12),
        "",
        "**Insight and findings:** Paired deltas are the best current evidence for whether an agent harness improves over Terminus. The deltas vary by model and benchmark, so claims should avoid saying one harness universally dominates.",
        "",
        "## Study 7: HaborMix Selection",
        "",
        "**Method:** Candidate tasks must be reliable, bounded, discriminative, and non-degenerate. The selection score rewards positive correlation with overall agent+model strength, observed variance, moderate difficulty, and observation count. I cap selection at 6 tasks per benchmark to avoid overrepresenting large benchmarks.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(PAPER_TABLE_DIR / 'harbormix_candidate_tasks.csv')}`",
        f"- `{md_path(PAPER_TABLE_DIR / 'harbormix_selection_by_benchmark.csv')}`",
        f"- `{md_path(TASK_STUDY_DIR / 'task_frontier_or_saturated_watchlist.csv')}`",
        "",
        report_image("harbormix_selection_diagnostics.png", "HaborMix selection diagnostics"),
        "",
        report_image("task_reliable_difficulty_composition.png", "Reliable bounded task difficulty composition"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(selection_by_benchmark, ["benchmark", "difficulty_tier", "selected_tasks", "mean_selection_score"], 14),
        "",
        f"- Selected {len(selected_tasks)} diversified candidate tasks.",
        "",
        "**Insight and findings:** HaborMix selection is quantitative and auditable: it balances discriminativeness, difficulty, coverage, and benchmark diversity rather than taking the largest benchmarks wholesale.",
        "",
        "## Study 8: Task Aggregate vs Benchmark-Level Score Alignment",
        "",
        "**Method:** For each benchmark, I average benchmark-relative task scores and correlate that aggregate with the benchmark-level benchmark-relative score across agent+model rows.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(PAPER_TABLE_DIR / 'task_to_benchmark_alignment.csv')}`",
        "",
        report_image("task_to_benchmark_alignment.png", "Task aggregate vs benchmark score alignment"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(alignment_good, ["benchmark", "n_reliable_bounded_tasks", "spearman_agent_model_correlation"], 12),
        "",
        "**Insight and findings:** Strong alignment means the task matrix explains the benchmark-level score; weak alignment flags benchmarks whose aggregation rule or metric scale needs closer inspection.",
        "",
        "## Cross-Study Story",
        "",
        "The emerging story is that benchmark diversity matters more than a single aggregate leaderboard. Coverage filtering removes sparse columns from the main benchmark-level claims. Within the retained benchmarks, model identity is usually more explanatory than agent identity, but agent effects vary sharply by model and benchmark. BenchPress-style predictability analysis finds benchmarks that are redundant enough to compress and benchmarks that add distinct signal. The task-level layer then answers a different question: which items are representative, which are hard to predict, and which form a balanced HaborMix candidate set. Terminus paired deltas are the fairest current way to talk about harness improvement.",
        "",
        "## Not Completed Yet",
        "",
        "- Trial reliability, pass@k, efficiency curves, token/tool cost analysis, and trajectory failure taxonomy still require per-trial run records.",
        "- Full IRT/DIF still requires repeated binary/calibrated task outcomes or enough dense task observations to fit stable item-response models.",
        "- Provider scaling analysis still requires external model metadata such as provider family, parameter scale, release date, and inference budget.",
        "",
    ]
    (PAPER_REPORT_DIR / "analysis_story.md").write_text("\n".join(report_lines))

    findings_lines = [
        "# Key Findings for Paper Drafting",
        "",
        f"1. Use {len(included_benchmarks)} coverage-filtered benchmarks for benchmark-level claims; keep sparse benchmarks in appendix/provisional analysis.",
        "2. Model identity is the larger overall factor, but the model-vs-agent balance varies by benchmark; use the per-benchmark role plot for qualified claims.",
        "3. Separate model and agent dimensions. The useful agent evidence is paired lift over `terminus-2` for the same model, not an unqualified agent+model leaderboard.",
        "4. BenchPress-style predictability applies here: redundant benchmarks can be compressed; least-predictable benchmarks should be preserved for behavioral breadth.",
        "5. Task predictability and task representativeness are distinct: hard-to-predict tasks are stress tests, while representative tasks are compact proxies for a benchmark.",
        f"6. The current task-level filter yields {len(selected_tasks)} diversified candidate tasks for HaborMix-style selection.",
        "7. Task-to-benchmark alignment should be used as a sanity check before interpreting benchmark-level scores from task-level tables.",
        "",
        "Primary reference file: `output/paper/reports/analysis_story.md`.",
    ]
    (PAPER_REPORT_DIR / "key_findings.md").write_text("\n".join(findings_lines))
