from __future__ import annotations

from ..core import *


KEY_TABLE_SUBDIRS = {
    "analysis_data_provenance": "provenance",
    "imputation_diagnostics_summary": "provenance",
    "benchmark_agent_model_scores": "leaderboards",
    "benchmark_scores_long": "leaderboards",
    "benchmark_mini_leaderboards": "leaderboards",
    "task_benchmark_reliable_summary": "task_level",
    "task_to_benchmark_alignment": "task_level",
    "task_within_benchmark_similarity": "task_level",
    "task_cross_benchmark_similarity": "task_level",
    "task_representative_tasks": "task_level",
    "task_predictability_ranked": "task_level",
    "harbormix_selected_tasks": "harbormix",
    "harbormix_selection_by_benchmark": "harbormix",
    "terminus_delta_by_model": "benchmark_level",
}


def key_table_path(name: str) -> Path:
    subdir = KEY_TABLE_SUBDIRS.get(name, "benchmark_level" if name.startswith("benchmark") else "task_level")
    return KEY_TABLE_DIR / subdir / f"{name}.csv"


def write_key_analysis_reports(
    study_tables: dict[str, pd.DataFrame],
    benchmark_result: ImputationResult,
    task_result: ImputationResult,
    included_benchmarks: list[str],
    mini_leaderboard_figures: list[str],
) -> None:
    filter_table = study_tables["benchmark_filtering"]
    provenance = study_tables["analysis_data_provenance"]
    imputation_diagnostics = study_tables["imputation_diagnostics_summary"]
    agent_model_scores = study_tables["benchmark_agent_model_scores"]
    model_effects = study_tables["benchmark_model_adjusted_effects"]
    agent_effects = study_tables["benchmark_agent_adjusted_effects"]
    variance_filtered = study_tables["benchmark_variance_decomposition_filtered"]
    benchmark_role = study_tables["benchmark_model_agent_role_by_benchmark"]
    benchmark_clusters = study_tables["benchmark_similarity_clusters"]
    redundancy = study_tables["benchmark_redundancy_pairs_filtered"]
    uniqueness = study_tables["benchmark_uniqueness_filtered"]
    agent_lift = study_tables["benchmark_agent_lift_vs_terminus"]
    terminus_by_model = study_tables["terminus_delta_by_model"]
    task_summary = study_tables["task_benchmark_reliable_summary"]
    alignment = study_tables["task_to_benchmark_alignment"]
    task_similarity = study_tables["task_within_benchmark_similarity"]
    task_cross_similarity = study_tables["task_cross_benchmark_similarity"]
    representative_tasks = study_tables["task_representative_tasks"]
    task_predictability = study_tables["task_predictability_ranked"]
    selected_tasks = study_tables["harbormix_selected_tasks"]
    selection_by_benchmark = study_tables["harbormix_selection_by_benchmark"]

    excluded = filter_table[~filter_table["include_in_key_analysis"]]
    redundant_high = redundancy[redundancy["spearman"] >= 0.75].sort_values("spearman", ascending=False)
    unique_low = uniqueness.sort_values("cv_r2_from_other_included_benchmarks")
    alignment_good = alignment[
        alignment["included_in_benchmark_level_key_filter"] & (alignment["n_reliable_bounded_tasks"] >= 3)
    ].sort_values("spearman_agent_model_correlation", ascending=False)
    task_pool = task_summary.sort_values("candidate_pool_tasks", ascending=False)
    role_gap = benchmark_role.assign(
        absolute_role_gap=lambda df: (df["model_partial_r2_over_agent"] - df["agent_partial_r2_over_model"]).abs()
    ).sort_values("absolute_role_gap", ascending=False)
    hard_tasks = task_predictability.sort_values("task_unpredictability_score", ascending=False)
    representative_top = representative_tasks.sort_values("useful_representativeness_score", ascending=False)
    key_tables = sorted(str(path.relative_to(KEY_TABLE_DIR)) for path in KEY_TABLE_DIR.rglob("*.csv"))
    key_figures = sorted(str(path.relative_to(KEY_FIGURE_DIR)) for path in KEY_FIGURE_DIR.rglob("*.png"))
    code_files = [
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'core')}/`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'preprocessing' / 'svd_imputation.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'coverage_filtering.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'intermediate_tables.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'model_agent_roles.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'benchmark_predictability.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'benchmark_similarity.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'leaderboards.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'terminus_comparison.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'task_alignment.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'task_selection.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'task_similarity.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'provenance.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'visualization')}/`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'reporting' / 'key_analysis_report.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'cli.py')}`",
    ]

    report_lines = [
        "# Key Analysis Cross-Benchmark Analysis",
        "",
        "This report is intended to be read directly. Figures and compact table previews are embedded inline; CSV paths are listed for exact numbers and reproducibility.",
        "",
        "## Directory Contract",
        "",
        f"- Key analysis tables: `{md_path(KEY_TABLE_DIR)}/`",
        f"- Key analysis figures: `{md_path(KEY_FIGURE_DIR)}/`",
        "- Layered table groups: `benchmark_level/`, `leaderboards/`, `task_level/`, `harbormix/`, and `provenance/`.",
        "- Layered figure groups: `benchmark_level/`, `leaderboards/`, `task_level/`, and `harbormix/`.",
        f"- Intermediate study outputs: `{md_path(INTERMEDIATE_STUDY_DIR)}/`",
        f"- Intermediate imputed matrices and diagnostics: `{md_path(PROCESSED_DIR)}/`",
        "",
        "The current preprocessing contract is task-first: task scores are SVD-filled, then benchmark scores are aggregated from the filled task matrix. The original benchmark matrix is retained as metadata and as a sanity check, but benchmark scores are not SVD-filled directly.",
        "",
        "BenchPress mapping note: Dimitris's BenchPress repo treats benchmark prediction as an explicit analysis problem, compares benchmark-regression and SVD families under held-out validation, and uses a blend because regression can be more accurate while SVD gives broader coverage. Our schema is task-rich rather than model-benchmark-only, so we map that lesson by using task-SVD for coverage, benchmark/task predictability tables for difficulty ranking, and task aggregate alignment as a diagnostic rather than blindly trusting every aggregate.",
        "",
        "Data provenance for the main studies:",
        "",
        *markdown_table(provenance, ["analysis", "primary_matrix", "processed_output"], 10),
        "",
        "Preprocessing diagnostics:",
        "",
        "Task imputation method: each score column is robustly centered and scaled after `log1p` for nonnegative unbounded columns; task SVD rank is selected by held-out observed-cell cross-validation; missing task cells are filled by iterative low-rank SVD reconstruction; observed task cells are restored exactly; filled task scores are inverse-transformed and clipped to the observed range of that task. Benchmark scores are then calculated as per-benchmark means across those task scores. Task-level imputation remains less stable than dense benchmark tables because the task matrix is much wider and sparser, so task conclusions are restricted to reliable bounded non-degenerate tasks.",
        "",
        *markdown_table(
            imputation_diagnostics,
            [
                "matrix",
                "preprocessing_method",
                "missing_fraction_before_processing",
                "selected_svd_rank",
                "task_svd_rank_used_for_benchmark_aggregation",
                "holdout_cells",
                "holdout_rmse_scaled_score_space",
                "holdout_mae_scaled_score_space",
            ],
            4,
        ),
        "",
        "## Research Question Coverage Checklist",
        "",
        "| Question | Status | Main artifacts |",
        "| --- | --- | --- |",
        "| Agent vs model role overall and per benchmark | covered | `tables/benchmark_level/benchmark_variance_decomposition_filtered.csv`, `tables/benchmark_level/benchmark_model_agent_role_by_benchmark.csv`, `figures/benchmark_level/benchmark_model_vs_agent_role.png` |",
        "| BenchPress-style benchmark predictability and hard-to-predict benchmarks/tasks | covered | `tables/benchmark_level/benchmark_uniqueness_filtered.csv`, `tables/task_level/task_predictability_ranked.csv`, benchmark/task predictability figures |",
        "| Benchmark/task similarity and clustering | covered | `tables/benchmark_level/benchmark_similarity_clusters.csv`, `tables/task_level/task_cross_benchmark_similarity.csv`, clustered heatmaps |",
        "| Representative tasks per benchmark | covered | `tables/task_level/task_representative_tasks.csv`, `figures/task_level/task_best_representatives.png` |",
        "| Mini-leaderboards grouped by similar benchmarks | covered | `tables/leaderboards/benchmark_mini_leaderboards.csv`, `figures/leaderboards/mini_leaderboards_cluster_*.png` |",
        "| Agent harness improvements over Terminus | covered | `tables/benchmark_level/benchmark_agent_lift_vs_terminus.csv`, `tables/benchmark_level/terminus_delta_by_model.csv`, Terminus heatmaps |",
        "| Quantitative HaborMix task selection | covered | `tables/harbormix/harbormix_selected_tasks.csv`, `tables/harbormix/harbormix_selection_by_benchmark.csv`, `figures/harbormix/harbormix_selection_diagnostics.png` |",
        "",
        "## Study 1: Coverage Filtering",
        "",
        "**Method:** Benchmark-level claims use benchmark aggregates derived from the task-SVD matrix, but coverage filtering still uses evidence metadata: at least 15 agent+model rows need some observed task evidence for that benchmark, and the missingness fields describe coverage before task-SVD filling. This filter keeps the key analysis story from leaning too heavily on filled task values.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_filtering'))}`",
        "",
        "**Result overview and analysis:**",
        f"- Included {len(included_benchmarks)} of {len(filter_table)} benchmarks.",
        f"- Excluded sparse benchmarks: {', '.join(excluded['benchmark'].tolist())}.",
        f"- Benchmark scores are task aggregates, not direct benchmark-SVD outputs; pre-aggregation benchmark missing fraction was {benchmark_result.missing_fraction:.3f}.",
        "",
        *markdown_table(filter_table, ["benchmark", "include_in_key_analysis", "observed_count", "missing_fraction", "task_cell_missing_fraction"], 12),
        "",
        "**Insight and findings:** Sparse columns should stay in appendix/provisional analysis until more experiments land. The main key analysis story should use the coverage-filtered benchmark set.",
        "",
        "## Study 2: Model vs Agent Roles",
        "",
        "**Method:** I fit fixed-effect regressions in two views. The overall view decomposes benchmark-relative score into model, agent, benchmark, and interaction terms. The per-benchmark view fits each benchmark separately and compares partial R2 from model after controlling for agent against partial R2 from agent after controlling for model.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_variance_decomposition_filtered'))}`",
        f"- `{md_path(key_table_path('benchmark_model_agent_role_by_benchmark'))}`",
        f"- `{md_path(key_table_path('benchmark_model_adjusted_effects'))}`",
        f"- `{md_path(key_table_path('benchmark_agent_adjusted_effects'))}`",
        "",
        report_image("benchmark_level/benchmark_variance_attribution.png", "Benchmark-level variance attribution"),
        "",
        report_image("benchmark_level/benchmark_model_vs_agent_role.png", "Per-benchmark model vs agent explanatory power"),
        "",
        report_image("benchmark_level/benchmark_model_adjusted_effects.png", "Model effects adjusted for agent and benchmark"),
        "",
        report_image("benchmark_level/benchmark_agent_adjusted_effects.png", "Agent effects adjusted for model and benchmark"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(variance_filtered, ["component", "partial_r2_over_other_main_effects", "r2", "type"], 7),
        "",
        "Benchmarks with the largest model-vs-agent role imbalance:",
        *markdown_table(role_gap, ["benchmark", "model_partial_r2_over_agent", "agent_partial_r2_over_model", "dominant_dimension"], 10),
        "",
        "**Insight and findings:** Model identity explains much more overall variation than agent identity, but the role varies by benchmark. Agent effects are more useful as benchmark-specific harnessing effects than as a universal main effect.",
        "",
        "## Study 3: Agent+Model Leaderboards",
        "",
        "**Method:** I keep `agent+model` rankings as descriptive mini-leaderboards. Per-benchmark mini-leaderboards use benchmark scores aggregated from SVD-filled tasks on each benchmark's original metric scale. Each mini-leaderboard shows all available agent+model rows, grouped by model with colored bars for agents, so the same plot makes model differences and agent harness differences visible. The aggregate top-agent plot uses mean within-benchmark score percentile, because averaging scores across benchmarks with different scales would be misleading.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_agent_model_scores'))}`",
        f"- `{md_path(key_table_path('benchmark_scores_long'))}`",
        f"- `{md_path(key_table_path('benchmark_mini_leaderboards'))}`",
        f"- `{md_path(key_table_path('benchmark_similarity_clusters'))}`",
        f"- `{md_path(KEY_FIGURE_DIR / 'leaderboards' / 'mini_leaderboards_cluster_*.png')}`",
        "",
        report_image("leaderboards/benchmark_agent_model_top_scores.png", "Top agent+model pairs on included benchmarks"),
        "",
        *[report_image(fig, f"Mini-leaderboards {fig}") for fig in mini_leaderboard_figures],
        "",
        "**Result overview and analysis:**",
        *markdown_table(agent_model_scores, ["rank", "agent_model", "mean_score_percentile_across_benchmarks", "original_benchmark_table_coverage"], 10),
        "",
        "**Insight and findings:** Benchmark scores should be read benchmark by benchmark. The percentile aggregate is a compact descriptive ranking only; it is not a causal agent claim because model and agent are entangled in the row identity.",
        "",
        "## Study 4: Benchmark Predictability and Similarity",
        "",
        "**Method:** Following the BenchPress idea, each included benchmark is predicted from the other included benchmarks using ridge regression with cross-validation over agent+model rows. Low or negative R2 means the benchmark is hard to reconstruct from the rest and likely contributes distinct information. Benchmark similarity uses Spearman correlation of agent+model score profiles and hierarchical clustering.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_uniqueness_filtered'))}`",
        f"- `{md_path(key_table_path('benchmark_redundancy_pairs_filtered'))}`",
        f"- `{md_path(key_table_path('benchmark_correlation_clustered'))}`",
        "",
        report_image("benchmark_level/benchmark_uniqueness_vs_coverage.png", "Benchmark uniqueness after coverage filtering"),
        "",
        report_image("benchmark_level/benchmark_similarity_clustered_heatmap.png", "Clustered benchmark similarity heatmap"),
        "",
        "**Result overview and analysis:**",
        "Hardest-to-predict benchmarks:",
        *markdown_table(unique_low, ["benchmark", "cv_r2_from_other_included_benchmarks", "cv_rmse"], 10),
        "",
        "Most similar benchmark pairs:",
        *markdown_table(redundant_high, ["left", "right", "spearman"], 10),
        "",
        "**Insight and findings:** Predictable benchmarks are candidates for compression; hard-to-predict benchmarks should be preserved when the goal is behavioral breadth. Similarity clusters are also the basis for the grouped mini-leaderboards.",
        "",
        "## Study 5: Task Similarity, Predictability, and Representatives",
        "",
        "**Method:** Task-level analysis uses reliable, bounded, non-degenerate tasks only. A task is hard to predict when its maximum absolute Spearman correlation to peer tasks in the same benchmark is low. Representativeness is no longer pure correlation with the benchmark aggregate: I compute a leave-one-out aggregate correlation and multiply it by observed cross-agent/model variance, so redundant but low-discrimination tasks no longer dominate. Within- and cross-benchmark task similarity use median absolute task-profile correlations. Difficulty tiers use mean task score thresholds: frontier <5%, hard 5-30%, medium 30-70%, easy 70-95%, saturated >95%.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('task_predictability_ranked'))}`",
        f"- `{md_path(key_table_path('task_representative_tasks'))}`",
        f"- `{md_path(key_table_path('task_within_benchmark_similarity'))}`",
        f"- `{md_path(key_table_path('task_cross_benchmark_similarity'))}`",
        "",
        report_image("task_level/task_hard_to_predict_ranked.png", "Hard-to-predict reliable tasks"),
        "",
        report_image("task_level/task_best_representatives.png", "Best representative task per benchmark"),
        "",
        report_image("task_level/task_similarity_benchmark_pair_heatmap.png", "Task similarity across benchmark pairs"),
        "",
        "**Result overview and analysis:**",
        "Hardest-to-predict reliable tasks:",
        *markdown_table(hard_tasks, ["benchmark", "task_id", "task_unpredictability_score", "difficulty_tier", "task_score"], 12),
        "",
        "Most representative tasks:",
        *markdown_table(representative_top, ["benchmark", "task_id", "useful_representativeness_score", "representativeness_score", "difficulty_tier", "task_score"], 12),
        "",
        "Benchmarks with strongest within-benchmark task similarity:",
        *markdown_table(task_similarity, ["benchmark", "n_reliable_tasks", "median_abs_task_similarity_within_benchmark"], 10),
        "",
        "**Insight and findings:** Task predictability and useful representativeness are different objectives. Representative tasks are the base set for predicting benchmark aggregates; hard-to-predict and difficult tasks are additional stress tests for broad coverage.",
        "",
        "## Study 6: Terminus Harnessing Effects",
        "",
        "**Method:** Terminus is treated as the fair baseline across models. For every model with both `terminus-2` and another agent row, I compute paired benchmark-relative score deltas while holding the model fixed.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_agent_lift_vs_terminus'))}`",
        f"- `{md_path(key_table_path('terminus_delta_by_model'))}`",
        f"- `{md_path(BENCHMARK_INTERMEDIATE_STUDY_DIR / 'benchmark_agent_lift_by_benchmark.csv')}`",
        "",
        report_image("benchmark_level/benchmark_agent_lift_heatmap.png", "Agent lift vs terminus by benchmark"),
        "",
        report_image("benchmark_level/terminus_delta_by_model_heatmap.png", "Agent lift vs terminus by model"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(agent_lift, ["agent", "mean_delta_vs_terminus", "win_rate_vs_terminus", "compared_models"], 6),
        "",
        *markdown_table(terminus_by_model, ["model", "agent", "mean_delta_vs_terminus", "win_rate_vs_terminus"], 12),
        "",
        "**Insight and findings:** Paired deltas are the best current evidence for whether an agent harness improves over Terminus. The deltas vary by model and benchmark, so claims should avoid saying one harness universally dominates.",
        "",
        "## Study 7: HaborMix Selection",
        "",
        "**Method:** Candidate tasks must be reliable and bounded. The final HaborMix selection targets a compact 100-200 task set, currently 160 tasks. It first includes a small base set of useful representative tasks per benchmark, then fills the remaining slots with a diversity-aware ranking over difficult, frontier-with-variance, unique/unpredictable, and high-composite tasks. The composite score combines useful representativeness, difficulty, unique/unpredictable signal, and cross-agent/model discrimination; it no longer excludes frontier or saturated items by construction. The broader scored pool is retained under intermediate studies for auditability.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('harbormix_selected_tasks'))}`",
        f"- `{md_path(key_table_path('harbormix_selection_by_benchmark'))}`",
        f"- `{md_path(TASK_INTERMEDIATE_STUDY_DIR / 'harbormix_scored_task_pool.csv')}`",
        f"- `{md_path(TASK_INTERMEDIATE_STUDY_DIR / 'task_frontier_or_saturated_watchlist.csv')}`",
        "",
        report_image("harbormix/harbormix_selection_diagnostics.png", "HaborMix selection diagnostics"),
        "",
        report_image("task_level/task_reliable_difficulty_composition.png", "Reliable bounded task difficulty composition"),
        "",
        report_image("task_level/task_reliable_difficulty_composition_percent.png", "Reliable bounded task difficulty composition by percentage"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(selection_by_benchmark, ["benchmark", "difficulty_tier", "selected_tasks", "mean_selection_score", "mean_representative_signal", "mean_unique_unpredictable_signal", "mean_difficulty_signal"], 14),
        "",
        f"- Selected {len(selected_tasks)} final HaborMix tasks from the broader scored candidate pool.",
        "",
        "**Insight and findings:** HaborMix selection is quantitative and auditable: representative tasks anchor the minimal benchmark-prediction base, while difficult and unique/unpredictable tasks add breadth.",
        "",
        "## Study 8: Task Aggregate vs Benchmark-Level Score Alignment",
        "",
        "**Method:** For each benchmark, I average benchmark-relative task scores and correlate that aggregate with the benchmark-level benchmark-relative score across agent+model rows. This is intentionally diagnostic rather than a hard gate: the new benchmark score is already the task aggregate, so this table mainly identifies benchmarks where reliable bounded tasks alone do or do not track the full task-derived benchmark aggregate.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('task_to_benchmark_alignment'))}`",
        "",
        report_image("task_level/task_to_benchmark_alignment.png", "Task aggregate vs benchmark score alignment"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(alignment_good, ["benchmark", "n_reliable_bounded_tasks", "spearman_agent_model_correlation", "alignment_quality"], 12),
        "",
        "**Insight and findings:** Strong alignment means the reliable bounded subset is a good proxy for the task-derived benchmark score. Weak alignment is not used to remove benchmarks automatically; it flags cases for manual benchmark/task inspection.",
        "",
        "## Cross-Study Story",
        "",
        "The emerging story is that benchmark diversity matters more than a single aggregate leaderboard. Coverage filtering removes sparse columns from the main benchmark-level claims. Within the retained benchmarks, model identity is usually more explanatory than agent identity, but agent effects vary sharply by model and benchmark. BenchPress-style predictability analysis finds benchmarks that are redundant enough to compress and benchmarks that add distinct signal. The task-level layer then answers a different question: which items are representative, which are hard to predict, and which form a balanced HaborMix candidate set. Terminus paired deltas are the fairest current way to talk about harness improvement.",
        "",
        "## Artifact Index",
        "",
        "All key analysis tables:",
        *[f"- `{md_path(KEY_TABLE_DIR / name)}`" for name in key_tables],
        "",
        "All key analysis figures:",
        *[report_image(name, name) for name in key_figures],
        "",
        "## Not Completed Yet",
        "",
        "- Trial reliability, pass@k, efficiency curves, token/tool cost analysis, and trajectory failure taxonomy still require per-trial run records.",
        "- Full IRT/DIF still requires repeated binary/calibrated task outcomes or enough dense task observations to fit stable item-response models.",
        "- Provider scaling analysis still requires external model metadata such as provider family, parameter scale, release date, and inference budget.",
        "",
    ]
    (KEY_REPORT_DIR / "analysis_story.md").write_text("\n".join(report_lines))

    findings_lines = [
        "# Key Findings for Key Analysis Drafting",
        "",
        f"1. Use {len(included_benchmarks)} coverage-filtered benchmarks for benchmark-level claims; keep sparse benchmarks in appendix/provisional analysis.",
        "",
        "The filtering table is now evidence-based on the task-first pipeline: benchmark scores come from task-SVD aggregates, while the missingness columns describe how much original task evidence supported each aggregate before filling.",
        "",
        report_image("benchmark_level/benchmark_uniqueness_vs_coverage.png", "Benchmark uniqueness after coverage filtering"),
        "",
        *markdown_table(filter_table, ["benchmark", "include_in_key_analysis", "observed_count", "task_cell_missing_fraction"], 8),
        "",
        "2. Model identity is the larger overall factor, but the model-vs-agent balance varies by benchmark; use the per-benchmark role plot for qualified claims.",
        "",
        "This is the clean answer to the agent-vs-model question: make the broad statement from the overall fixed-effect decomposition, then qualify it with per-benchmark partial R2 rather than collapsing everything into a single agent+model row label.",
        "",
        report_image("benchmark_level/benchmark_model_vs_agent_role.png", "Per-benchmark model vs agent explanatory power"),
        "",
        *markdown_table(role_gap, ["benchmark", "model_partial_r2_over_agent", "agent_partial_r2_over_model", "dominant_dimension"], 8),
        "",
        "3. Separate model and agent dimensions. The useful agent evidence is paired lift over `terminus-2` for the same model, not an unqualified agent+model leaderboard.",
        "",
        "The Terminus table should be read as a harnessing-effect estimate: the paired comparison holds model fixed where the same model appears under Terminus and another agent.",
        "",
        report_image("benchmark_level/terminus_delta_by_model_heatmap.png", "Agent lift vs terminus by model"),
        "",
        *markdown_table(agent_lift, ["agent", "mean_delta_vs_terminus", "win_rate_vs_terminus", "compared_models"], 6),
        "",
        "4. BenchPress-style predictability applies here: redundant benchmarks can be compressed; least-predictable benchmarks should be preserved for behavioral breadth.",
        "",
        "The benchmark-predictability result is deliberately separate from clustering: regression asks whether other benchmarks reconstruct a target, while the heatmap shows score-profile similarity. Use both when deciding whether two benchmarks are redundant.",
        "",
        report_image("benchmark_level/benchmark_similarity_clustered_heatmap.png", "Clustered benchmark similarity heatmap"),
        "",
        *markdown_table(unique_low, ["benchmark", "cv_r2_from_other_included_benchmarks", "cv_rmse"], 8),
        "",
        "5. Task predictability and task representativeness are distinct: hard-to-predict tasks are stress tests, while representative tasks are compact proxies for a benchmark.",
        "",
        "The representative-task score now uses leave-one-out aggregate correlation times task variance, so tasks that are merely typical but non-discriminative are less likely to dominate the selected base set.",
        "",
        report_image("task_level/task_hard_to_predict_ranked.png", "Hard-to-predict reliable tasks"),
        "",
        report_image("task_level/task_best_representatives.png", "Best representative task per benchmark"),
        "",
        *markdown_table(hard_tasks, ["benchmark", "task_id", "task_unpredictability_score", "difficulty_tier"], 8),
        "",
        *markdown_table(representative_top, ["benchmark", "task_id", "useful_representativeness_score", "difficulty_tier"], 8),
        "",
        f"6. The current HaborMix final set contains {len(selected_tasks)} diversified tasks.",
        "",
        "The HaborMix scorer is no longer centered on moderate difficulty. It first takes useful representative base tasks, then fills to a compact target size with difficult, frontier-with-variance, unique/unpredictable, and high-composite tasks.",
        "",
        report_image("harbormix/harbormix_selection_diagnostics.png", "HaborMix selection diagnostics"),
        "",
        *markdown_table(selection_by_benchmark, ["benchmark", "difficulty_tier", "selected_tasks", "mean_selection_score"], 10),
        "",
        "7. Task-to-benchmark alignment should be used as a sanity check before interpreting benchmark-level scores from task-level tables.",
        "",
        "This table is diagnostic rather than a gate. Weak alignment means the reliable bounded subset may not proxy the full task-derived aggregate well; it does not automatically remove the benchmark from the benchmark-level analysis.",
        "",
        report_image("task_level/task_to_benchmark_alignment.png", "Task aggregate vs benchmark score alignment"),
        "",
        *markdown_table(alignment_good, ["benchmark", "n_reliable_bounded_tasks", "spearman_agent_model_correlation", "alignment_quality"], 8),
        "",
        "Primary reference file: `output/key_analyses/reports/analysis_story.md`.",
    ]
    (KEY_REPORT_DIR / "key_findings.md").write_text("\n".join(findings_lines))
